"""add signups

Revision ID: bb80c5af007a
Revises: ccfff3555439
Create Date: 2025-07-13 00:34:30.344844

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bb80c5af007a"
down_revision: Union[str, Sequence[str], None] = "ccfff3555439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "INVITED", "ACCEPTED", "PROMOTED", "DEACTIVATED", name="signupstage"
            ),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ip", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_signup_email"), "signup", ["email"], unique=True)
    op.create_index(op.f("ix_signup_ip"), "signup", ["ip"], unique=False)
    op.create_index(op.f("ix_signup_status"), "signup", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signup_status"), table_name="signup")
    op.drop_index(op.f("ix_signup_ip"), table_name="signup")
    op.drop_index(op.f("ix_signup_email"), table_name="signup")
    op.drop_table("signup")
    # ### end Alembic commands ###
