"""init

Revision ID: ccfff3555439
Revises:
Create Date: 2025-07-12 22:16:07.754429

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ccfff3555439"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "program",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mcg_channels", sa.JSON(), nullable=True),
        sa.Column("full_channels", sa.JSON(), nullable=True),
        sa.Column("verification_required", sa.Boolean(), nullable=False),
        sa.Column("webhook", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("xoxc_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("xoxd_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_program_name"), "program", ["name"], unique=False)
    op.create_index(op.f("ix_program_webhook"), "program", ["webhook"], unique=False)
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("global_verification", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slack_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("admin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_slack_id"), "user", ["slack_id"], unique=True)
    op.create_table(
        "userprogramlink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["program.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "program_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userprogramlink")
    op.drop_index(op.f("ix_user_slack_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("settings")
    op.drop_index(op.f("ix_program_webhook"), table_name="program")
    op.drop_index(op.f("ix_program_name"), table_name="program")
    op.drop_table("program")
    # ### end Alembic commands ###
